spring:
  profiles:
    active: dev

com:
  tao:
    username: yangtao
---

spring:
  config:
    activate:
      on-profile: dev

name: dev.tao.com

---

spring:
  config:
    activate:
      on-profile: test

name: test.tao.com

---

spring:
  config:
    activate:
      on-profile: prod

name: prod.tao.com